/* generated by build.mjs — edit the template there, not this file */
'use strict';
const CACHE = 'narcan-e06ac7e60c';
const PRECACHE = [
  "/",
  "/card/",
  "/es/",
  "/404.html",
  "/manifest.json",
  "/sw-register.js",
  "/app.js?v=d9c763d9f4",
  "/data.js?v=56bb40b7f9",
  "/card/card.js?v=ba4307de9b",
  "/icon-192.png",
  "/icon-512.png",
  "/apple-touch-icon.png",
  "/fonts/InterVariable.woff2",
  "/fonts/InterVariable-Italic.woff2",
  "/fonts/Fraunces-Variable-latin.woff2",
  "/fonts/Fraunces-Variable-latin-ext.woff2",
  "/es/card/"
];

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(PRECACHE))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// network with a timeout so flaky connections fall back to cache fast
const fromNetwork = (req, ms) => new Promise((resolve, reject) => {
  const t = setTimeout(reject, ms, new Error('timeout'));
  fetch(req).then((res) => { clearTimeout(t); resolve(res); }, (err) => { clearTimeout(t); reject(err); });
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  if (req.mode === 'navigate') {
    e.respondWith((async () => {
      const cache = await caches.open(CACHE);
      try {
        const res = await fromNetwork(req, 3500);
        if (res.ok) cache.put(req, res.clone());
        return res;
      } catch {
        return (await cache.match(req, { ignoreSearch: true }))
            || (await cache.match('/'))
            || Response.error();
      }
    })());
    return;
  }

  e.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req);
    if (hit) return hit;
    const res = await fetch(req);
    if (res.ok && ['script', 'style', 'font', 'image'].includes(req.destination)) {
      cache.put(req, res.clone());
    }
    return res;
  })());
});
